from enum import Enum

class BoatTransitInformation(Enum):
    KAID_BOAT_TRANSIT_TIME_IN_SECONDS = 2 * 60 # 2minutes
    REALM_BOAT_TRANSIT_TIME_IN_SECONDS = 5 * 60 # 5minutes
    REALM_BOAT_DOCK_TIME_IN_SECONDS = 1 * 60 # 1minute
    KAID_BOAT_DOCK_TIME_IN_SECONDS = 2 * 60 # 2minutes
    KAID_BOAT_ROUNDTRIP_TIME_IN_SECONDS = 2 * (KAID_BOAT_TRANSIT_TIME_IN_SECONDS + KAID_BOAT_DOCK_TIME_IN_SECONDS)
    REALM_BOAT_ROUNDTRIP_TIME_IN_SECONDS = 3 * (REALM_BOAT_TRANSIT_TIME_IN_SECONDS + REALM_BOAT_DOCK_TIME_IN_SECONDS)
